### ISSUE TITLE
Rails can be suspended in mid-air

### ISSUE THREAD

**Issue by Insane-96** [Creator256/Better-Railroads#9]
Just place a rail on a block and remove the block. The rail will stay there

**Comment by JillSwift** [comment]
[Intended](https://github.com/Creator256/Better-Railroads/issues/2)

**Comment by Insane-96** [comment]
Wtf makes no sense. Sadly I think the dev left this mod

**Comment by Creator256** [comment]
Nope still here. Classes started again so didn't have time. Collecting bugs and adding new things. Rails are supposed to be able to be suspended, it is intended.

**Comment by Insane-96** [comment]
Wow, cool. Hope to see an update soon. I would add a config for the suspended rails thing by the way.
